name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checa o repositório
      - uses: actions/checkout@v4

      # Configura o Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Ajuste para a versão que você preferir

      # Instala dependências (se necessário, já no package.json)
      - name: Install dependencies
        run: npm install

      # Executa o linting
      - name: Run markdown lint
        run: |
          npx remark . --use remark-preset-lint-consistent --frail
